

# This file was *autogenerated* from the file RSA_KnownHighBits.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_16 = Integer(16)#!/usr/bin/env python3
from random import randint
from Crypto.Util.number import *
from hashlib import sha256, md5
from ecdsa import SECP256k1
from ecdsa.ecdsa import Public_key, Private_key, Signature
from sage.all import *
# FLAG = open("flag", 'r').read()

E = SECP256k1
G, n = E.generator, E.order
print(n)
d = randint(1 , n)

pubkey = Public_key(G, d*G)
prikey = Private_key(pubkey, d)
print(f'P = ({pubkey.point.x()}, {pubkey.point.y()})')
print(prikey.secret_multiplier)
print(d)
print(E)
print(G)
print(n)

msg = '1'
h = sha256(msg.encode()).digest()
h1 = int.from_bytes(sha256(msg.encode()).digest(), 'big')
k = int(md5(b'secret').hexdigest() + md5(long_to_bytes(prikey.secret_multiplier) + h).hexdigest(), 16 )
K = int('5ebe2294ecd0e0f08eab7690d2a6ee69' + '00000000000000000000000000000000', 16)
M = int('1' + '00000000000000000000000000000000', 16)
print('K = ' +str(K))
print('M = ' + str(M))
print('n^1/2 = ' + str(float(n)**1/2))
print(M < n**1/2)
k1 = k
print('k1 ' + str(k % n))
sig = prikey.sign(bytes_to_long(h), k)
print(f'({sig.r}, {sig.s})')
r1 = sig.r
s1 = sig.s

msg = '2'
h = sha256(msg.encode()).digest()
h2 = int.from_bytes(sha256(msg.encode()).digest(), 'big')
k = int(md5(b'secret').hexdigest() + md5(long_to_bytes(prikey.secret_multiplier) + h).hexdigest(), _sage_const_16 )
k2 = k
print('k2 ' + str(k2 % n))
sig = prikey.sign(bytes_to_long(h), k)
print(f'({sig.r}, {sig.s})')
r2 = sig.r
s2 = sig.s

t = -s2*r1 * inverse_mod(s1*r2, n)
u = r1 * h2 * inverse_mod(s1 * r2, n) - h1 * inverse_mod(s1, n)

L = matrix(ZZ, [[n, 0, 0], [t, 1, 0], [K+K*t+u, 0, M]])
B = L.LLL()
print(B)
print(M)

for row in B.rows():
    if row[2] == M and row[1] < 0:
        print(-row[0])
        print(row[1])
        k1 = -row[0] + K
        k2 = row[1] + K
        break
print(k1 % n)
print(k2 % n)
print(d)
# G = PolynomialRing(Zmod(n), names=('x', 'y',)); (x, y,) = G._first_ngens(2)
# f  = x + t * y + u
# print(f.small_roots(X = K))

